"""Mapping from Supabase institutes.name → CollegePravesh URL slug.

Keys must match the `name` column in the Supabase `institutes` table EXACTLY.
Slugs follow CollegePravesh pattern: https://www.collegepravesh.com/engineering-colleges/{slug}/

Set value to None for colleges that do NOT have a CollegePravesh page.
"""

COLLEGE_PRAVESH_SLUGS: dict[str, str | None] = {
    # ── IITs ─────────────────────────────────────────────────
    "IIT (BHU) Varanasi": "iit-bhu-varanasi",
    "IIT (ISM) Dhanbad": "iit-ism-dhanbad",
    "IIT Bhilai": "iit-bhilai",
    "IIT Bhubaneswar": "iit-bhubaneswar",
    "IIT Bombay": "iit-bombay",
    "IIT Delhi": "iit-delhi",
    "IIT Dharwad": "iit-dharwad",
    "IIT Gandhinagar": "iit-gandhinagar",
    "IIT Goa": "iit-goa",
    "IIT Guwahati": "iit-guwahati",
    "IIT Hyderabad": "iit-hyderabad",
    "IIT Indore": "iit-indore",
    "IIT Jammu": "iit-jammu",
    "IIT Jodhpur": "iit-jodhpur",
    "IIT Kanpur": "iit-kanpur",
    "IIT Kharagpur": "iit-kharagpur",
    "IIT Madras": "iit-madras",
    "IIT Mandi": "iit-mandi",
    "IIT Palakkad": "iit-palakkad",
    "IIT Patna": "iit-patna",
    "IIT Roorkee": "iit-roorkee",
    "IIT Ropar": "iit-ropar",
    "IIT Tirupati": "iit-tirupati",

    # ── NITs ─────────────────────────────────────────────────
    "NIT, Tiruchirappalli": "nit-trichy",
    "NIT, Warangal": "nit-warangal",
    "NIT Karnataka, Surathkal": "nit-surathkal",
    "NIT, Rourkela": "nit-rourkela",
    "NIT Calicut": "nit-calicut",
    "NIT, Kurukshetra": "nit-kurukshetra",
    "NIT Durgapur": "nit-durgapur",
    "NIT, Silchar": "nit-silchar",
    "NIT, Jamshedpur": "nit-jamshedpur",
    "NIT Patna": "nit-patna",
    "NIT Hamirpur": "nit-hamirpur",
    "NIT Agartala": "nit-agartala",
    "NIT Meghalaya": "nit-meghalaya",
    "NIT Nagaland": "nit-nagaland",
    "NIT Goa": "nit-goa",
    "NIT Puducherry": "nit-puducherry",
    "NIT Raipur": "nit-raipur",
    "NIT Sikkim": "nit-sikkim",
    "NIT Arunachal Pradesh": "nit-arunachal-pradesh",
    "NIT, Manipur": "nit-manipur",
    "NIT, Mizoram": "nit-mizoram",
    "NIT, Uttarakhand": "nit-uttarakhand",
    "NIT, Srinagar": "nit-srinagar",
    "NIT, Andhra Pradesh": "nit-andhra-pradesh",
    "NIT Delhi": "nit-delhi",
    "MNIT Jaipur": "mnit-jaipur",
    "MANIT Bhopal": "manit-bhopal",
    "MNNIT Allahabad": "mnnit-allahabad",
    "SVNIT, Surat": "nit-surat",
    "VNIT, Nagpur": "vnit-nagpur",
    "Dr.BRAMNIT, Jalandhar": "nit-jalandhar",
    "Indian Institute of Engineering Science and Technology, Shibpur": "iiest-shibpur",

    # ── IIITs ────────────────────────────────────────────────
    "ABV-IIITM Gwalior": "iiitm-gwalior",
    "IIIT, Allahabad": "iiit-allahabad",
    "IIIT, Design & Manufacturing, Kancheepuram": "iiitdm-kancheepuram",
    "IIIT Design & Manufacturing Kurnool, Andhra Pradesh": "iiitdm-kurnool",
    "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur": "iiitdm-jabalpur",
    "IIIT Guwahati": "iiit-guwahati",
    "IIIT Lucknow": "iiit-lucknow",
    "IIIT (IIIT) Nagpur": "iiit-nagpur",
    "IIIT (IIIT) Pune": "iiit-pune",
    "IIIT (IIIT) Ranchi": "iiit-ranchi",
    "IIIT (IIIT), Sri City, Chittoor": "iiit-sri-city",
    "IIIT (IIIT)Kota, Rajasthan": "iiit-kota",
    "IIIT Bhagalpur": "iiit-bhagalpur",
    "IIIT Bhopal": "iiit-bhopal",
    "IIIT Manipur": "iiit-manipur",
    "IIIT Surat": "iiit-surat",
    "IIIT Tiruchirappalli": "iiit-trichy",
    "IIIT(IIIT) Dharwad": "iiit-dharwad",
    "IIIT(IIIT) Kalyani, West Bengal": "iiit-kalyani",
    "IIIT(IIIT) Kilohrad, Sonepat, Haryana": "iiit-sonepat",
    "IIIT(IIIT) Kottayam": "iiit-kottayam",
    "IIIT(IIIT) Una, Himachal Pradesh": "iiit-una",
    "IIIT(IIIT), Vadodara, Gujrat": "iiit-vadodara",
    "IIIT, Agartala": "iiit-agartala",
    "IIIT, Vadodara International Campus Diu (IIITVICD)": None,  # No CP page
    "INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR": None,  # Duplicate / no CP page
    "Indian institute of information technology, Raichur, Karnataka": "iiit-raichur",

    # ── GFTIs ────────────────────────────────────────────────
    "Assam University, Silchar": None,
    "BIT, Deoghar Off-Campus": None,
    "BIT, Mesra, Ranchi": "bit-mesra",
    "BIT, Patna Off-Campus": None,
    "CU Jharkhand": None,
    "Central University of Haryana": None,
    "Central University of Jammu": None,
    "Central University of Rajasthan, Rajasthan": None,
    "Central institute of Technology Kokrajar, Assam": None,  # No CollegePravesh page
    "Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)": None,
    "Gati Shakti Vishwavidyalaya, Vadodara": None,
    "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal": None,
    "Gurukula Kangri Vishwavidyalaya, Haridwar": None,
    "Indian Institute of Carpet Technology, Bhadohi": None,
    "Indian Institute of Handloom Technology(IIHT), Varanasi": None,
    "Indian Institute of Handloom Technology, Salem": None,
    "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar": None,
    "Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)": None,
    "Institute of Infrastructure, Technology, Research and Management-Ahmedabad": None,
    "Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)": None,
    "IntIIIT, Bhubaneswar": "iiit-bhubaneswar",
    "IntIIIT, Naya Raipur": "iiit-naya-raipur",
    "Islamic University of Science and Technology Kashmir": None,
    "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad": None,
    "JNU, Delhi": None,
    "Mizoram University, Aizawl": None,
    "National Institute of Advanced Manufacturing Technology, Ranchi": None,
    "National Institute of Electronics and Information Technology, Ajmer (Rajasthan)": None,
    "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)": None,
    "National Institute of Electronics and Information Technology, Gorakhpur (UP)": None,
    "National Institute of Electronics and Information Technology, Patna (Bihar)": None,
    "National Institute of Electronics and Information Technology, Ropar (Punjab)": None,
    "National Institute of Food Technology Entrepreneurship and Management, Kundli": None,  # No CollegePravesh page (only niftem-thanjavur exists)
    "National Institute of Food Technology Entrepreneurship and Management, Thanjavur": "niftem-thanjavur",
    "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh": None,  # No CollegePravesh page
    "North-Eastern Hill University, Shillong": None,
    "PEC, Chandigarh": "pec-chandigarh",
    "Puducherry Technological University, Puducherry": None,
    "Rajiv Gandhi National Aviation University, Fursatganj, Amethi (UP)": None,
    "Sant Longowal Institute of Engineering and Technology": None,  # No CollegePravesh page
    "School of Engineering, Tezpur University, Napaam, Tezpur": "soe-tezpur",
    "School of Planning & Architecture, Bhopal": None,
    "School of Planning & Architecture, New Delhi": None,
    "School of Planning & Architecture: Vijayawada": None,
    "School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur": None,
    "Shri G. S. Institute of Technology and Science Indore": None,
    "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir": None,  # No CollegePravesh page
    "UoH": None,  # University of Hyderabad — no engineering CP page
}

