"""Mapping from Supabase institutes.name → official website URL.

Keys must match the `name` column in the Supabase `institutes` table EXACTLY.
"""

OFFICIAL_URLS: dict[str, str | None] = {
    # ── IITs ─────────────────────────────────────────────────
    "IIT (BHU) Varanasi":                    "https://www.iitbhu.ac.in",
    "IIT (ISM) Dhanbad":                     "https://www.iitism.ac.in",
    "IIT Bhilai":                            "https://www.iitbhilai.ac.in",
    "IIT Bhubaneswar":                       "https://www.iitbbs.ac.in",
    "IIT Bombay":                            "https://www.iitb.ac.in",
    "IIT Delhi":                             "https://www.iitd.ac.in",
    "IIT Dharwad":                           "https://www.iitdh.ac.in",
    "IIT Gandhinagar":                       "https://www.iitgn.ac.in",
    "IIT Goa":                               "https://www.iitgoa.ac.in",
    "IIT Guwahati":                          "https://www.iitg.ac.in",
    "IIT Hyderabad":                         "https://www.iith.ac.in",
    "IIT Indore":                            "https://www.iiti.ac.in",
    "IIT Jammu":                             "https://www.iitjammu.ac.in",
    "IIT Jodhpur":                           "https://www.iitj.ac.in",
    "IIT Kanpur":                            "https://www.iitk.ac.in",
    "IIT Kharagpur":                         "https://www.iitkgp.ac.in",
    "IIT Madras":                            "https://www.iitm.ac.in",
    "IIT Mandi":                             "https://www.iitmandi.ac.in",
    "IIT Palakkad":                          "https://www.iitpkd.ac.in",
    "IIT Patna":                             "https://www.iitp.ac.in",
    "IIT Roorkee":                           "https://www.iitr.ac.in",
    "IIT Ropar":                             "https://www.iitrpr.ac.in",
    "IIT Tirupati":                          "https://www.iittp.ac.in",

    # ── NITs ─────────────────────────────────────────────────
    "NIT, Tiruchirappalli":                  "https://www.nitt.edu",
    "NIT, Warangal":                         "https://www.nitw.ac.in",
    "NIT Karnataka, Surathkal":              "https://www.nitk.ac.in",
    "NIT, Rourkela":                         "https://www.nitrkl.ac.in",
    "NIT Calicut":                           "https://www.nitc.ac.in",
    "NIT, Kurukshetra":                      "https://www.nitkkr.ac.in",
    "NIT Durgapur":                          "https://www.nitdgp.ac.in",
    "NIT, Silchar":                          "https://www.nits.ac.in",
    "NIT, Jamshedpur":                       "https://www.nitjsr.ac.in",
    "NIT Patna":                             "https://www.nitp.ac.in",
    "NIT Hamirpur":                          "https://www.nith.ac.in",
    "NIT Agartala":                          "https://www.nita.ac.in",
    "NIT Meghalaya":                         "https://www.nitm.ac.in",
    "NIT Nagaland":                          "https://www.nitnagaland.ac.in",
    "NIT Goa":                               "https://www.nitgoa.ac.in",
    "NIT Puducherry":                        "https://www.nitpy.ac.in",
    "NIT Raipur":                            "https://www.nitrr.ac.in",
    "NIT Sikkim":                            "https://www.nitsikkim.ac.in",
    "NIT Arunachal Pradesh":                 "https://www.nitap.ac.in",
    "NIT, Manipur":                          "https://www.nitmanipur.ac.in",
    "NIT, Mizoram":                          "https://www.nitmz.ac.in",
    "NIT, Uttarakhand":                      "https://www.nituk.ac.in",
    "NIT, Srinagar":                         "https://www.nitsri.ac.in",
    "NIT, Andhra Pradesh":                   "https://www.nitandhra.ac.in",
    "NIT Delhi":                             "https://www.nitdelhi.ac.in",
    "MNIT Jaipur":                           "https://www.mnit.ac.in",
    "MANIT Bhopal":                          "https://www.manit.ac.in",
    "MNNIT Allahabad":                       "https://www.mnnit.ac.in",
    "SVNIT, Surat":                          "https://www.svnit.ac.in",
    "VNIT, Nagpur":                          "https://www.vnit.ac.in",
    "Dr.BRAMNIT, Jalandhar":                 "https://www.nitj.ac.in",
    "Indian Institute of Engineering Science and Technology, Shibpur": "https://www.iiest.ac.in",

    # ── IIITs ────────────────────────────────────────────────
    "ABV-IIITM Gwalior":                     "https://www.iiitm.ac.in",
    "IIIT, Allahabad":                        "https://www.iiita.ac.in",
    "IIIT, Design & Manufacturing, Kancheepuram": "https://www.iiitdm.ac.in",
    "IIIT Design & Manufacturing Kurnool, Andhra Pradesh": "https://www.iiitk.ac.in",
    "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur": "https://www.iiitdmj.ac.in",
    "IIIT Guwahati":                         "https://www.iiitg.ac.in",
    "IIIT Lucknow":                          "https://www.iiitl.ac.in",
    "IIIT (IIIT) Nagpur":                    "https://www.iiitn.ac.in",
    "IIIT (IIIT) Pune":                      "https://www.iiitp.ac.in",
    "IIIT (IIIT) Ranchi":                    "https://www.iiitranchi.ac.in",
    "IIIT (IIIT), Sri City, Chittoor":       "https://www.iiits.ac.in",
    "IIIT (IIIT)Kota, Rajasthan":            "https://www.iiitkota.ac.in",
    "IIIT Bhagalpur":                        "https://www.iiitbh.ac.in",
    "IIIT Bhopal":                           "https://www.iiitbhopal.ac.in",
    "IIIT Manipur":                          "https://www.iiitmanipur.ac.in",
    "IIIT Surat":                            "https://www.iiitsurat.ac.in",
    "IIIT Tiruchirappalli":                  "https://www.iiitt.ac.in",
    "IIIT(IIIT) Dharwad":                    "https://www.iiitdwd.ac.in",
    "IIIT(IIIT) Kalyani, West Bengal":       "https://www.iiitkalyani.ac.in",
    "IIIT(IIIT) Kilohrad, Sonepat, Haryana": "https://www.iiitkl.ac.in",
    "IIIT(IIIT) Kottayam":                   "https://www.iiitkottayam.ac.in",
    "IIIT(IIIT) Una, Himachal Pradesh":      "https://www.iiituna.ac.in",
    "IIIT(IIIT), Vadodara, Gujrat":          "https://www.iiitvadodara.ac.in",
    "IIIT, Agartala":                        "https://www.iiit-agartala.ac.in",
    "IIIT, Vadodara International Campus Diu (IIITVICD)": None,
    "INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR": None,
    "Indian institute of information technology, Raichur, Karnataka": "https://www.iiitrl.ac.in",
    "IntIIIT, Bhubaneswar":                  "https://www.iiit-bh.ac.in",
    "IntIIIT, Naya Raipur":                  "https://www.iiitnr.ac.in",

    # ── GFTIs ────────────────────────────────────────────────
    "Assam University, Silchar":             "https://www.aus.ac.in",
    "BIT, Mesra, Ranchi":                    "https://www.bitmesra.ac.in",
    "BIT, Deoghar Off-Campus":               None,
    "BIT, Patna Off-Campus":                 None,
    "CU Jharkhand":                          "https://www.cuj.ac.in",
    "Central University of Haryana":         "https://www.cuh.ac.in",
    "Central University of Jammu":           "https://www.cujammu.ac.in",
    "Central University of Rajasthan, Rajasthan": "https://www.curaj.ac.in",
    "Central institute of Technology Kokrajar, Assam": "https://www.cit.ac.in",
    "Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)": "https://www.csvtu.ac.in",
    "Gati Shakti Vishwavidyalaya, Vadodara": "https://www.gsv.ac.in",
    "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal": "https://www.gkciet.ac.in",
    "Gurukula Kangri Vishwavidyalaya, Haridwar": "https://www.gkv.ac.in",
    "Indian Institute of Carpet Technology, Bhadohi":  "https://www.iict.ac.in",
    "Indian Institute of Handloom Technology(IIHT), Varanasi": None,
    "Indian Institute of Handloom Technology, Salem": None,
    "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar": "https://www.ictmumbai.edu.in",
    "Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)": "https://www.dhsgsu.ac.in",
    "Institute of Infrastructure, Technology, Research and Management-Ahmedabad": "https://www.iitram.ac.in",
    "Institute of Technology, Guru Ghasidas Vishwavidyalaya (A Central University), Bilaspur, (C.G.)": "https://www.ggu.ac.in",
    "Islamic University of Science and Technology Kashmir": "https://www.iust.ac.in",
    "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad": "https://www.allduniv.ac.in",
    "JNU, Delhi":                            "https://www.jnu.ac.in",
    "Mizoram University, Aizawl":            "https://www.mzu.edu.in",
    "National Institute of Advanced Manufacturing Technology, Ranchi": "https://www.niamt.ac.in",
    "National Institute of Electronics and Information Technology, Ajmer (Rajasthan)": "https://www.nielit.gov.in",
    "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)": "https://www.nielit.gov.in",
    "National Institute of Electronics and Information Technology, Gorakhpur (UP)": "https://www.nielit.gov.in",
    "National Institute of Electronics and Information Technology, Patna (Bihar)": "https://www.nielit.gov.in",
    "National Institute of Electronics and Information Technology, Ropar (Punjab)": "https://www.nielit.gov.in",
    "National Institute of Food Technology Entrepreneurship and Management, Kundli": "https://www.niftem.ac.in",
    "National Institute of Food Technology Entrepreneurship and Management, Thanjavur": "https://www.niftem-t.ac.in",
    "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh": "https://www.nerist.ac.in",
    "North-Eastern Hill University, Shillong": "https://www.nehu.ac.in",
    "PEC, Chandigarh":                       "https://www.pec.ac.in",
    "Puducherry Technological University, Puducherry": "https://www.pec.edu",
    "Rajiv Gandhi National Aviation University, Fursatganj, Amethi (UP)": "https://www.rgnau.ac.in",
    "Sant Longowal Institute of Engineering and Technology": "https://www.sliet.ac.in",
    "School of Engineering, Tezpur University, Napaam, Tezpur": "https://www.tezu.ernet.in",
    "School of Planning & Architecture, Bhopal": "https://www.spab.ac.in",
    "School of Planning & Architecture, New Delhi": "https://www.spa.ac.in",
    "School of Planning & Architecture: Vijayawada": "https://www.spav.ac.in",
    "School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur": "https://www.ggu.ac.in",
    "Shri G. S. Institute of Technology and Science Indore": "https://www.sgsits.ac.in",
    "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir": "https://www.smvdu.ac.in",
    "UoH":                                   "https://www.uohyd.ac.in",
}


# ── Section URL hints ─────────────────────────────────────────────────────────
# Fallback path patterns tried when auto-discovering section pages.

SECTION_PATHS = {
    "faculty":        ["/faculty", "/people/faculty", "/departments", "/academic/faculty",
                       "/academics/faculty", "/about/faculty"],
    "placements":     ["/placements", "/training-and-placement", "/placement",
                       "/career", "/t-and-p", "/cdc"],
    "research":       ["/research", "/research-and-development", "/r-and-d", "/research-centres"],
    "infrastructure": ["/infrastructure", "/facilities", "/campus-facilities"],
    "admissions":     ["/admissions", "/admission", "/how-to-apply"],
    "academics":      ["/academics", "/programmes", "/programs", "/academic-programmes"],
    "international":  ["/international", "/global-initiatives", "/international-relations",
                       "/office-of-international-relations"],
    "student_life":   ["/student-activities", "/student-life", "/campus-life", "/clubs"],
}

